### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [1]:
import numpy as np

In [55]:
vector = np.random.uniform(0, 1, 10)
display(vector)
display(vector.shape)

array([0.58009324, 0.00664144, 0.55441691, 0.51337928, 0.07771443,
       0.81244082, 0.70036644, 0.69008998, 0.35133768, 0.29195303])

(10,)

In [56]:
vector = np.random.rand(10)
display(vector)
display(vector.shape)

array([0.91636583, 0.46219347, 0.57198686, 0.18590721, 0.69192393,
       0.70555145, 0.77585262, 0.31107172, 0.44000671, 0.57787993])

(10,)

In [18]:
matrix = np.array([[11,14,17],[20,23,26],[29,32,35]])
display(matrix)
display(matrix.shape)

array([[11, 14, 17],
       [20, 23, 26],
       [29, 32, 35]])

(3, 3)


### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [57]:
vector10 = (vector + 10).round(2)
vector10

array([10.92, 10.46, 10.57, 10.19, 10.69, 10.71, 10.78, 10.31, 10.44,
       10.58])

In [22]:
matrix2 = matrix * 2
matrix2

array([[22, 28, 34],
       [40, 46, 52],
       [58, 64, 70]])

In [58]:
vector_sqt = vector ** 2
vector_sqt

array([0.83972633, 0.21362281, 0.32716896, 0.03456149, 0.47875873,
       0.49780285, 0.60194729, 0.09676561, 0.19360591, 0.33394521])


### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [43]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [40]:
result_matrix = np.dot(B, A)

display(result_matrix, result_matrix.shape)

array([[0.7281, 0.5202],
       [0.2034, 0.2846]])

(2, 2)

In [48]:
# К-сть стовбців 1-ї матриці має бути рівна к-сті рядків 2-ї. Якщо множимо С на result_matrix, тобто (2,1) * (2,2), буде помилка. Якщо навпаки, тобто (2,2) * (2,1), то розмірність має бути (2,1).

result_matrix_C = np.dot(result_matrix, C)
print(result_matrix_C)

[[0.5202]
 [0.2846]]


In [49]:
# У будь-якому порядку множення матриць в даному випадку, розмірність результуючої має вийти (2,2).

result_matrix_D = np.dot(result_matrix, D)
print(result_matrix_D)

[[0.5202 0.7281]
 [0.2846 0.2034]]



### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [50]:
result_matrix_T = result_matrix.T
print(result_matrix_T)

[[0.7281 0.2034]
 [0.5202 0.2846]]


In [68]:
vector_T = vector.T
print(vector_T)

# Немає різниці в розмірності, так як numpy не транспонує одномірний масив через просто .T (чомусь?)

[0.91636583 0.46219347 0.57198686 0.18590721 0.69192393 0.70555145
 0.77585262 0.31107172 0.44000671 0.57787993]


In [70]:
column_vector = np.expand_dims(vector, 1)
print(column_vector)

[[0.91636583]
 [0.46219347]
 [0.57198686]
 [0.18590721]
 [0.69192393]
 [0.70555145]
 [0.77585262]
 [0.31107172]
 [0.44000671]
 [0.57787993]]


In [65]:
vector == column_vector

array([[ True, False, False, False, False, False, False, False, False,
        False],
       [False,  True, False, False, False, False, False, False, False,
        False],
       [False, False,  True, False, False, False, False, False, False,
        False],
       [False, False, False,  True, False, False, False, False, False,
        False],
       [False, False, False, False,  True, False, False, False, False,
        False],
       [False, False, False, False, False,  True, False, False, False,
        False],
       [False, False, False, False, False, False,  True, False, False,
        False],
       [False, False, False, False, False, False, False,  True, False,
        False],
       [False, False, False, False, False, False, False, False,  True,
        False],
       [False, False, False, False, False, False, False, False, False,
         True]])

In [66]:
column_vector_T = column_vector.T

display(column_vector_T, column_vector_T.shape)

array([[0.91636583, 0.46219347, 0.57198686, 0.18590721, 0.69192393,
        0.70555145, 0.77585262, 0.31107172, 0.44000671, 0.57787993]])

(1, 10)