В цьому домашньому завданні ми реалізуємо логістичну регресію на `numpy`.
Ці завдання допоможуть вам ґрунтовно засвоїти основні концепції логістичної регресії та реалізувати їх на практиці 🔥

#### Завдання 1: Реалізація функції сигмоїди
1. З використанням `numpy` напишіть функцію `sigmoid(z)` для обчислення значення сигмоїди згідно з формулою:
   $$
   \sigma(z) = \frac{1}{1 + e^{-z}}
   $$
2. Використовуючи цю функцію, обчисліть значення сигмоїди для наступних даних: $ z = [-2, -1, 0, 1, 2] $. Виведіть результат обчислень.


In [4]:
import numpy as np

In [5]:
def sigmoid(z):
  sig = 1 / (1 + np.exp(-z))
  return sig

In [6]:
z = np.array([-2,-1,0,1,2]) #z описує лінійну комбінацію ознак (як лінійна функція, де z = theta0 + theta1 * x1...)

In [7]:
sigmoid(z)

array([0.11920292, 0.26894142, 0.5       , 0.73105858, 0.88079708])

***ПОЯСНЕННЯ***

***СИГМОЇДА ПЕРЕТВОРЮЄ ЛІНІЙНУ ОЦІНКУ НА ІМОВІРНОСТІ***

* z описує лінійну комбінацію ознак (як лінійна функція, де z = theta0 + theta1 * x1...) - ця лінійна частина логістичної регресії описує **логарифм шансів**
* **шанс** - це співвідношення імовірності класу 1 до імовірності класу 0, тобто скільки разів клас 1 очікуєтьтся на один клас 0. Розраховується як імовірність шансу 1 / 1 - імовірність шансу 1
* однак ймовірність класу 1 (адже в нас лог. регресія описує ймовірність шансу, що y = 1) має бути в межах [0 ; 1]
* **сигмоїда перетворює логарифми шансів у зрозумілі ймовірності**



#### Завдання 2: Реалізація функції гіпотези для логістичної регресії
1. Напишіть функцію `hypothesis(theta, X)`, яка обчислює гіпотезу для логістичної регресії, використовуючи функцію сигмоїди. Формула гіпотези:
   $$
   h_\theta(x) = \sigma(\theta^T x) = \frac{1}{1 + e^{-\theta^T x}}
   $$
2. Використайте функцію `hypothesis` для обчислення значень гіпотези для наступних даних:
   
   $\theta = [0.5, -0.5]$
   
   $X = \begin{bmatrix} 1 & 2 \\ 1 & -1 \\ 1 & 0 \\ 1 & 1 \end{bmatrix}$

  Виведіть результат обчислень.


In [8]:
def hypothesis(theta, X):
  hyp = sigmoid(X.dot(theta.T))
  return hyp

In [9]:
theta = np.array([0.5,-0.5])
X = np.array([[1,2],[1,-1],[1,0],[1,1]])

In [10]:
hypothesis(theta, X)

array([0.37754067, 0.73105858, 0.62245933, 0.5       ])

***ПОЯСНЕННЯ***

***ГІПОТЕЗА ОБЧИСЛЮЄ ПРОГНОЗОВАНІ ІМОВІРНОСТІ ДЛЯ КОНКРЕТНИХ СПОСТЕРЕЖЕНЬ***

1. маємо вектор коефіцієнтів `theta`, де перший коеф. 0.5 - **вільний**, другий -0.5 - **коеф. при X**
2. маємо матрицю X, де перший стовпець значення 1 при вільному коеф., другий - значення Х при другому коеф.
3. через функцію сигмоїди рахуємо прогнозовані лінійні оцінки шансів з заданими коеф. та Х і переводимо в прогнозовані ймовірності класу 1



***ТРАКТУВАННЯ КОЕФІЦЄНТІВ***

Логарифм (буквально) шансів = лінійна оцінка

Коефіцієнти тут прямо інтерпретуються, як в лінійній регресії: на скільки зміниться логарифм шансів класу 1 при зміні X на одиницю. Однак інтерпретація з логарифмами шансів складна.

При збільшенні Х на 1 та шляхом підрахунків отримуємо рівняння, яке *при знятті логарифму через експоненту* виводить рівняння, де **нові шанси = старі шанси * експоненту по коеф.** Іншими словами, при збільшенні Х на 1 старі шанси множаться на експоненту.

**Аби зрозуміти *у скільки разів* змінилися шанси, ми ділимо нові на старі.
Отримуємо `odds ratio` = експонента по коефіцієнту.**

***Коефіцієнт `theta 0`***

Це **базова оцінка логарифму шансів при Х = 0**, тобто як за умовчанням зміниться ймовірність класу 1 при відсутності впливу інших змінних.
Тут при відсутності впливу X логарифм шансів зросте на 0.5.

***Коефіцієнт `theta j`***

Це **коефіцієнти при незалежній змінній**. Тут лише одна, тому `theta 1`.
Збільшення X на 1 зменшує логарифм шансів класу 1 на 0.5 (бо -0.5).

`OR` = експонента по -0.5 = приблизно 0.607. Отже, нові шанси = старі шанси * 0.607

**Зі збільшенням Х на одиницю шанси класу 1 становлять 0.607 попередніх шансів**. Іншими словами, нові шанси будуть постійно зменшуватись, так як становитимуть лише 60% від старих. В імовірностях це 1-0.607 = приблизно 0.393 (39.3%).

**!ВАЖЛИВО!**

39.9% - це на скільки зменшиться ШАНСИ класу 1, а не зміна імовірності настання класу 1. Так як імовірність = шанс класу 1  / 1 + шанс класу 1, і вона має окремо розраховуватись перетворенням шансів назад в імовірності та підрахунок зміни.

#### Завдання 3: Реалізація функції для підрахунку градієнтів фукнції втрат
1. Напишіть функцію `compute_gradient(theta, X, y)`, яка обчислює градієнти функції втрат для логістичної регресії. Формула для обчислення градієнта:
   $$
   \frac{\partial L(\theta)}{\partial \theta_j} = \frac{1}{m} \sum_{i=1}^{m} \left[ (h_\theta(x^{(i)}) - y^{(i)}) x_j^{(i)} \right]
   $$
2. Використайте функцію `compute_gradient` для обчислення градієнтів для наступних даних:

  $\theta = [0.5, -0.5]$

  $X = \begin{bmatrix} 1 & 2 \\ 1 & -1 \\ 1 & 0 \\ 1 & 1 \end{bmatrix}$

  $y = [1, 0, 1, 0]$

  Виведіть результат обчислень.

In [11]:
def compute_gradient(theta, X, y):
  errors = hypothesis(theta, X) - y #отримання помилок прогнозів
  grad = 1/len(X) * errors.dot(X) #сума добутку помилок на Х йде через dot() та множення матриць, тому не застосовується np.sum()
  return grad

In [12]:
theta = np.array([0.5,-0.5])
X = np.array([[1,2],[1,-1],[1,0],[1,1]])
y = np.array([1,0,1,0])

In [13]:
compute_gradient(theta, X, y)

array([ 0.05776464, -0.36899431])

***ПОЯСНЕННЯ***

***ГРАДІЄНТ ПОКАЗУЄ, ЯК ЗМІНИТИ КОЕФІЦІЄНТИ ДЛЯ ЗМЕНШЕННЯ Ф-ЦІЇ ВТРАТ***

* для `theta 0` Х = 1, тому по формулі це фактично буде середня помилка прогнозованих ймовірностей - наскільки в середньому відхиляється модель. Тобто на 5.7% модель прогнозує імовірність класу 1 модель частіше, ніж фактично.

* для `theta 1` на 36.8% модель прогнозує імовірність класу 1 модель рідше, ніж фактично. Тобто для зменшення ф-ції втрат необхідно коеф. збільшити (це видно з розрахунку нового коеф. по градієнтному спуску, який збільшується).



#### Завдання 4: Реалізація повного батч градієнтного спуску

**Задача:**
1. Напишіть функцію `full_batch_gradient_descent(X, y, lr=0.1, epochs=100)`, яка реалізує алгоритм Full градієнтного спуску для логістичної регресії. Використовуйте такі формули:
   - Гіпотеза: $ h_\theta(x) = \sigma(\theta^T x) $
   - Оновлення параметрів: $ \theta_j := \theta_j - \alpha \frac{\partial L(\theta)}{\partial \theta_j} $
2. Використайте функцію `full_batch_gradient_descent` для обчислення параметрів моделі на наступних даних:

  $X = \begin{bmatrix} 1 & 2 \\ 1 & -1 \\ 1 & 0 \\ 1 & 1 \end{bmatrix}$

  $y = [1, 0, 1, 0]$

  Увага! Матриця $X$ вже має стовпець одиниць і передбачається, що це. - стовпець для intercept - параметра зсуву.

  Виведіть результат обчислень.


In [14]:
def full_batch_gradient_descent(X, y, lr=0.1, epochs=100):
  theta = np.zeros(X.shape[1]) #будуємо початковий вектор коефіціїнтів з 0-ів за формою Х (а конкретно за 1 рядком та к-стю стовбців = к-сті стовбців Х)

  for epoch in range(epochs):
    gradient = compute_gradient(theta, X, y)
    theta = theta - lr * gradient
  return theta


In [15]:
X = np.array([[1,2],[1,-1],[1,0],[1,1]])
y = np.array([1,0,1,0])

In [18]:
theta_fbgd = full_batch_gradient_descent(X, y, lr=0.1, epochs=100)
theta_fbgd

array([-0.2893693 ,  0.77655125])

#### Завдання 5. Обчислення точності моделі

1. Напишіть функцію `predict_proba(theta, X)`, яка використовує знайдені параметри $\theta$ для обчислення ймовірностей належності поточного прикладу з даних до класу $y=1$ на основі значень $\sigma(\theta^T x)$.

2. Напишіть функцію `predict(theta, X, threshold=0.5)`, яка обчислює клас з передбаченої імовірності належності екземпляра до класу 1 з порогом 0.5. Тобто якщо ймовірність менше 0.5, то передбачаємо клас 0, інакше клас 1.

3. Напишіть функцію `accuracy(y_true, y_pred)`, яка обчислює точність моделі, визначивши частку правильно передбачених класів.

  Формула метрики Accuracy:
  $$
  \text{Accuracy} = \frac{\sum_{i=1}^{m} I(\hat{{y}^{(i)}} = y^{(i)})}{m}
  $$

  де $\hat{{y}^{(i)}}$ - передбачене значення класу, $I$ - індикаторна функція (яка дорівнює 1, якщо умова виконується, і 0 - якщо ні), $m$ - кількість прикладів.

4. Обчисліть з використанням даних в завданні 4 $X$, $y$ та обчислених коефіцієнтах $\theta$ та виведіть на екран:
  - передбачені моделлю імовірності належності кожного з екземплярів в матриці `X` до класу 1
  - класи кожного екземпляра з матриці `X`
  - точність моделі.

In [50]:
from sklearn.metrics import accuracy_score

In [35]:
def predict_proba(theta, X):
  y_pred_probabilities = hypothesis(theta, X)
  return y_pred_probabilities

In [43]:
def predict(theta, X, threshold):
  y_pred_probabilities = predict_proba(theta, X)
  y_pred_class = (y_pred_probabilities >= threshold).astype(int) # твердження вертає True, яке переводиться в числовий тип: True = 1, False = 0
  return y_pred_class

In [56]:
def accuracy(y_fact, y_pred):
    correct = (y_fact == y_pred).mean()
    return correct

In [37]:
X = np.array([[1,2],[1,-1],[1,0],[1,1]])
y = np.array([1,0,1,0])

In [30]:
# Передбачені моделлю імовірності належності кожного з екземплярів в матриці X до класу 1
y_pred_probabilities = predict_proba(theta_fbgd, X)
y_pred_probabilities

array([0.77966809, 0.25617965, 0.42815828, 0.61944235])

In [44]:
# Переведення прогнозованих імовірностей в класи кожного екземпляра з матриці X
y_pred_class = predict(theta_fbgd, X, 0.5)
y_pred_class

array([1, 0, 0, 1])

In [58]:
# Точність моделі = к-сть правильних прогнозів / загальну к-сть прогнозів
model_accuracy = accuracy(y, y_pred_class)
model_accuracy

np.float64(0.5)